import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { PrismaClient } from '@prisma/client';
import { useState } from "react";
import Link from 'next/link';

const prisma = new PrismaClient();

export async function getServerSideProps() {
    const data = await prisma.movie.findMany();
    return {
        props: {
            data
        }
    }
}

export default function Home({ data }) {

    const [ formData, setFormData ] = useState({});
    const [ movies, setMovies ] = useState(data);

    const saveMovie = async (e) => {
        e.preventDefault();
        setMovies([...movies, formData]);
        const res = await fetch('/api/movies',{
            method: 'POST',
            body: JSON.stringify(formData)
        });
        return await res.json();
    };
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <ul className={styles.movielist}>
              { movies.map((movie) => {
                  return (
                      <li key={movie.id}>
                          <span><strong>Title: {movie.title}</strong></span>
                          <span>Year: {movie.year}</span>
                          <span>Description: {movie.description}</span>
                          <Link href={`/movies/${movie.slug}`}><a>
                              More about this movie
                          </a></Link>
                      </li>
                  );
              }) }
          </ul>
          <form className={styles.movieform} onSubmit={saveMovie}>
              <input type="text" placeholder="Title" name="title" onChange={e => setFormData({ ...formData, title: e.target.value })}/>
              <input type="text" placeholder="Year" name="year" onChange={e => setFormData({ ...formData, year: +e.target.value })} />
              <textarea name="description" id="" cols="30" rows="10" placeholder="Description" onChange={e => setFormData({ ...formData, description: e.target.value })} />
              <input type="text" placeholder="Slug" name="slug" onChange={e => setFormData({ ...formData, slug: e.target.value })} />
              <button type="submit">Add movie</button>
          </form>
      </main>
    </div>
  )
}
